--DDL: Data Definition Languge(데이터 정의어)
--테이블 생성
CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(20),
    MEMBER_FWD VARCHAR2(20),
    MEMBER_NAME VARCHAR2(20)
);
DROP TABLE MEMBER;

--코멘트 작성
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디' ; --COLUMN에 COMMENT(코멘트)를 추가한다. 
COMMENT ON COLUMN MEMBER.MEMBER_FWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원이름';

--테이블 명 수정
ALTER TABLE MEMBER RENAME TO STUDENT;

--테이블 컬럼명 수정
ALTER TABLE MEMBER  --테이블의 컬럼 추가
ADD (MEMBER_GENDER VARCHAR2(2));

ALTER TABLE MEMBER  --테이블의 컬럼 추가 
ADD (MEMBER_ADDRESS VARCHAR2(100));

ALTER TABLE MEMBER  --테이블의 컬럼 삭제
DROP COLUMN MEMBER_ADDRESS;

ALTER TABLE STUDENT      --테이블의 컬럼이름 변경
RENAME COLUMN MEMBER_ADDRESSS TO STUDENT_ADDRESS;

ALTER TABLE MEMBER      --테이블의 컬럼 자료형 크기 변경
MODIFY MEMBER_ADDRESSS VARCHAR2(1000); 


--STDEUNT TABLE의 COLUMN명 번경
ALTER TABLE STUDENT
RENAME COLUMN MEMBER_ID TO STUDENT_ID;

ALTER TABLE STUDENT
RENAME COLUMN MEMBER_FWD TO STUDENT_FWD;

ALTER TABLE STUDENT
RENAME COLUMN MEMBER_NAME TO STUDENT_NAME;

ALTER TABLE STUDENT
RENAME COLUMN MEMBER_GENDER TO STUDENT_GENDER;

ALTER TABLE STUDENT
RENAME COLUMN STUDNET_ADRESS TO STUDENT_ADDRESS;

--STUDENT TABLE -> MEMBER TABLE로  이름변경
ALTER TABLE STUDENT RENAME TO MEMBER;

ALTER TABLE MEMBER
RENAME COLUMN STUDENT_ID TO MEMBER_ID;

ALTER TABLE MEMBER
RENAME COLUMN STUDENT_FWD TO MEMBER_FWD;

ALTER TABLE MEMBER
RENAME COLUMN STUDENT_NAME TO MEMBER_NAME;

ALTER TABLE MEMBER
RENAME COLUMN STUDENT_GENDER TO MEMBER_GENDER;

ALTER TABLE MEMBER
RENAME COLUMN STUDENT_ADDRESS TO MEMBER_ADDRESS;

--작업순서: 1.테이블생성 2.테이블삭제 3.컬럼추가 4.컬럼삭제 5.컬럼수정,컬럼명변경 6.테이블명 변경
















