CREATE TABLE MEMBER( -- 테이블 생성
    MEMBER_ID VARCHAR2(20), -- 컬럼명 자료형(크기),
    MEMBER_PWD VARCHAR2(20),
    MEMBER_NAME VARCHAR2(20)
);

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디'; -- 컨트롤+엔터:실행
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원이름';

DROP TABLE MEMBER; -- 테이블 삭제

ALTER TABLE MEMBER RENAME TO STUDENT;

ALTER TABLE MEMBER
ADD (MEMBER_GENDER VARCHAR2(2));

ALTER TABLE MEMBER
ADD (MEMBER_ADRESS VARCHAR2(100)); -- 테이블에 컬럼 추가

ALTER TABLE MEMBER
DROP COLUMN MEMBER_ADDRESS;  -- 테이블 컬럼 삭제

ALTER TABLE MEMBER
ADD (MEMBER_ADDRESS VARCHAR2(100)); -- 테이블 컬럼 추가

ALTER TABLE MEMBER
RENAME COLUMN MEMBER_ADDRESS TO MEMBER_ADDR; -- 테이블 컬럼명 변경

ALTER TABLE MEMBER
MODIFY MEMBER_ADDR VARCHAR2(100); -- 테이블 컬럼 자료형 크기 변경

ALTER TABLE STUDENT
RENAME COLUMN MEMBER_ID TO STUDENT_ID;
ALTER TABLE STUDENT
RENAME COLUMN MEMBER_PWD TO STUDENT_PWD;
ALTER TABLE STUDENT
RENAME COLUMN MEMBER_NAME TO STUDENT_NAME;
ALTER TABLE STUDENT
RENAME COLUMN MEMBER_GENDER TO STUDENT_GENDER;
ALTER TABLE STUDENT
RENAME COLUMN MEMBER_ADDR TO STUDENT_ADDR;

ALTER TABLE STUDENT RENAME TO MEMBER;

ALTER TABLE MEMBER
RENAME COLUMN STUDENT_ID TO MEMBER_ID;
ALTER TABLE MEMBER
RENAME COLUMN STUDENT_PWD TO MEMBER_PWD;
ALTER TABLE MEMBER
RENAME COLUMN STUDENT_NAME TO MEMBER_NAME;
ALTER TABLE MEMBER
RENAME COLUMN STUDENT_GENDER TO MEMBER_GENDER;
ALTER TABLE MEMBER
RENAME COLUMN STUDENT_ADDR TO MEMBER_ADDR;


INSERT INTO "KHUSER"."MEMBER" (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, 
MEMBER_GENDER, MEMBER_ADDR) 
VALUES ('khuser01', 'pass01', '일용자', 'M', '서울');

INSERT INTO MEMBER(MEMBER_ID, MEMBER_PWD, MEMBER_NAME, MEMBER_GENDER, MEMBER_ADDR)
VALUES ('khuser02', 'pass02', '이용자', 'F', '경기');
COMMIT;

INSERT INTO MEMBER VALUES('khuser03', 'pass03', '삼용자', 'M', '서울');
COMMIT;