INSERT INTO STUDENT VALUES(NULL, NULL, NULL, NULL, NULL);
COMMIT;

CREATE TABLE STUDENT_NOTNULL(
    STUDENT_ID VARCHAR2(20) NOT NULL, -- 컬럼 레벨 제약조건 설정
    STUDENT_PWD VARCHAR2(30) NOT NULL,
    STUDENT_NAME VARCHAR2(30) NOT NULL,
    STUDENT_GENDER VARCHAR2(3),
    STUDENT_ADDRESS VARCHAR2(500)
    -- NOT NULL은 테이블 레벨 설정 불가능
);
INSERT INTO STUDENT_NOTNULL VALUES(NULL,NULL,NULL,NULL,NULL);
INSERT INTO STUDENT_NOTNULL VALUES('khuser01','pass01','일용자',NULL,NULL);
COMMIT;

CREATE TABLE STUDENT_UNIQUE(
    STUDENT_ID VARCHAR2(20), -- 컬럼 레벨 제약조건 설정
    STUDENT_PWD VARCHAR2(30) CONSTRAINT NOTNULL_PWD NOT NULL,
    STUDENT_NAME VARCHAR2(30) CONSTRAINT NOTNULL_NAME NOT NULL,
    STUDENT_GENDER VARCHAR2(3) CONSTRAINT CHECK_GENDER CHECK(STUDENT_GENDER IN('남','여')),
    STUDENT_ADDRESS VARCHAR2(500),
    CONSTRAINT UNQ_STUDENT_ID UNIQUE(STUDENT_ID) -- 테이블 레벨 제약조건 설정
);
DROP TABLE STUDENT_UNIQUE;
INSERT INTO STUDENT_UNIQUE VALUES('khuser01','pass01','일용자','남',null);
INSERT INTO STUDENT_UNIQUE VALUES('khuser02', 'pass02', '이용자', '여', null);
INSERT INTO STUDENT_UNIQUE VALUES('khuser03', 'pass03', '삼용자', 'M', null);
COMMIT;

CREATE TABLE STUDENT_PRIMARYKEY(
    STUDENT_ID VARCHAR2(20) CONSTRAINT STUDENT_ID_PK PRIMARY KEY,
    STUDENT_PWD VARCHAR2(30) CONSTRAINT NOTNULL_PWD2 NOT NULL,
    STUDENT_NAME VARCHAR2(30)CONSTRAINT NOTNULL_NAME2 NOT NULL,
    STUDENT_GENDER VARCHAR2(3),
    STUDENT_ADDRESS VARCHAR2(500)
);
DROP TABLE STUDENT_PRIMARYKEY;
INSERT INTO STUDENT_PRIMARYKEY VALUES('khuser01','pass01','일용자','남','서울');

CREATE TABLE USER_GRADE(
    GRADE_CODE NUMBER PRIMARY KEY,
    GRADE_NAME VARCHAR2(30) NOT NULL
);

INSERT INTO USER_GRADE VALUES(10, '일반회원');
INSERT INTO USER_GRADE VALUES(20, '우수회원');
INSERT INTO USER_GRADE VALUES(30, '특별회원');
COMMIT;

CREATE TABLE USER_FOREIGNKEY(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) UNIQUE,
    USER_WPD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30),
    GENDER VARCHAR2(3),
    PHONE VARCHAR2(30),
    EMAIL VARCHAR2(50),
    GRADE_CODE NUMBER REFERENCES USER_GRADE(GRADE_CODE) ON DELETE SET NULL
);
CREATE TABLE USER_FOREIGNKEY(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) UNIQUE,
    USER_WPD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30),
    GENDER VARCHAR2(3),
    PHONE VARCHAR2(30),
    EMAIL VARCHAR2(50),
    GRADE_CODE NUMBER REFERENCES USER_GRADE(GRADE_CODE) ON DELETE CASCADE
);
DROP TABLE USER_FOREIGNKEY;
INSERT INTO USER_FOREIGNKEY VALUES(1, 'user01', 'pass01', '홍길동', '남', '010-1234-5678', 'hong123@kh.or.kr', 10);
INSERT INTO USER_FOREIGNKEY VALUES(2, 'user02', 'pass02', '이순신', '남', '010-5678-9012', 'lee123@kh.or.kr', 20);
INSERT INTO USER_FOREIGNKEY VALUES(3, 'user03', 'pass03', '유관순', '여', '010-9999-3131', 'yoo123@kh.or.kr', 30);
INSERT INTO USER_FOREIGNKEY VALUES(4, 'user04', 'pass04', '임꺽정', '남', '010-3322-2323', 'lim123@kh.or.kr', 10);
COMMIT;