--NOT NULL은 제약조건 추가, 삭제시 MODIFY를 쓴다
CREATE USER KHUSER IDENTIFIED BY KHUSER;
--KHUSER에 권한부여
GRANT CONNECT TO KHUSER;
GRANT RESOURCE TO KHUSER;
-- 계정생성
CREATE USER TEST01 IDENTIFIED BY TEST01;
GRANT CONNECT,RESOURCE TO TEST01;
--권한부여 & 회수 -->모두 SYSTEM계정에서 한다
GRANT SELECT ON KHUSER.COFFEE TO TEST01; --SYSTEM 계정에서 KHUSER.COFFEE테이블 을 SELECT할 수 있게 TEST01로 권한을 준다   
REVOKE SELECT ON KHUSER.COFFEE FROM TEST01; -- SYSTEM 계정에서 KHUSER.COFFEE테이블의 SELECT할 수있는 권한을 TEST01에서 뺏는다

--권한
GRANT INSERT ON KHUSER.COFFEE TO TEST01; 
REVOKE INSERT ON KHUSER.COFFEE FROM TEST01;















--계정생성
CREATE USER KH IDENTIFIED BY KH;
GRANT CONNECT, RESOURCE TO KH; --권한부여
